name: dart_code_metrics_plugin_loader
description: This pubspec determines the version of the analyzer plugin to load.
version: 5.7.5

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  dart_code_metrics: 5.7.5

dev_dependencies:
  lints: ">=2.1.1 <3.0.0"
